---
# This playbook deploys the entire Mesos cluster infrastructure.
# RUN: ansible-playbook --ask-sudo-pass -i hosts site.yml

- name: deploy and configure the mesos masters
  hosts: mesos_masters
  user: vagrant
  port: 22
  become: yes
  become_method: sudo
  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos_masters"] }

- name: deploy and configure the mesos slaves
  hosts: mesos_slaves
  user: vagrant
  port: 22
  become: yes
  become_method: sudo
  roles:
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos_slaves"] }
