---
# handlers file for mesos
- name: Start mesos-master
  systemd: name=mesos-master state=started daemon_reload=yes
  become: yes

- name: Stop mesos-master
  systemd: name=mesos-master state=stopped daemon_reload=yes
  become: yes

- name: Start mesos-slave
  systemd: name=mesos-slave state=started daemon_reload=yes
  become: yes

- name: Restart mesos-slave
  systemd: name=mesos-slave state=restarted daemon_reload=yes
  become: yes

- name: Stop mesos-slave
  systemd: name=mesos-slave state=stopped daemon_reload=yes
  become: yes

- name: Restart zookeeper
  systemd: name=zookeeper  state=stopped daemon_reload=yes
  become: yes

- name: Stop zookeeper
  systemd: name=zookeeper state=stopped daemon_reload=yes
  become: yes
