---
# handlers file for mesos
- name: Start mesos-master
  shell: start mesos-master
  become: yes

- name: Stop mesos-master
  shell: stop mesos-master
  become: yes

- name: Start mesos-slave
  shell: start mesos-slave
  become: yes

- name: Restart mesos-slave
  shell: restart mesos-slave
  become: yes

- name: Stop mesos-slave
  shell: stop mesos-slave
  become: yes

- name: Restart zookeeper
  shell: restart zookeeper
  become: yes

- name: Stop zookeeper
  shell: stop zookeeper
  become: yes
